name: Create Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from build
      uses: bettermarks/action-artifact-download@0.3.0
      with:
        repo: growtopiajaw/ubuntu-20_22-diff
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: patch.svf
        rename: patch-downloaded.svf    
        wait_seconds: 60
    - name: Set Up Dependencies
      run: |
        sudo apt install zstd -y
        zstd --ultra -22 -T0 --auto-threads=logical --progress -v patch-downloaded.svf -o patch.zstd
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        name: patch.zstd
        path: ${{ github.workspace }}/patch.zstd
        retention-days: 90
